/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户账号信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccount implements Serializable {

    private static final long serialVersionUID = 1027861797;

    private Integer   id;
    private Integer   userId;
    private Integer   identifyType;
    private String    identifier;
    private String    credential;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Boolean   status;

    public TAccount() {}

    public TAccount(TAccount value) {
        this.id = value.id;
        this.userId = value.userId;
        this.identifyType = value.identifyType;
        this.identifier = value.identifier;
        this.credential = value.credential;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
    }

    public TAccount(
        Integer   id,
        Integer   userId,
        Integer   identifyType,
        String    identifier,
        String    credential,
        Timestamp createTime,
        Timestamp updateTime,
        Boolean   status
    ) {
        this.id = id;
        this.userId = userId;
        this.identifyType = identifyType;
        this.identifier = identifier;
        this.credential = credential;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getIdentifyType() {
        return this.identifyType;
    }

    public void setIdentifyType(Integer identifyType) {
        this.identifyType = identifyType;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getCredential() {
        return this.credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccount (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(identifyType);
        sb.append(", ").append(identifier);
        sb.append(", ").append(credential);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
