/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 文章标签关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArticleTag implements Serializable {

    private static final long serialVersionUID = 1576965659;

    private Integer id;
    private Integer articleId;
    private Integer tagId;

    public TArticleTag() {}

    public TArticleTag(TArticleTag value) {
        this.id = value.id;
        this.articleId = value.articleId;
        this.tagId = value.tagId;
    }

    public TArticleTag(
        Integer id,
        Integer articleId,
        Integer tagId
    ) {
        this.id = id;
        this.articleId = articleId;
        this.tagId = tagId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TArticleTag (");

        sb.append(id);
        sb.append(", ").append(articleId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
