/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 文章表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArticle implements Serializable {

    private static final long serialVersionUID = 1562269251;

    private Integer   id;
    private String    title;
    private String    summary;
    private String    author;
    private String    source;
    private Integer   sort;
    private Integer   clickNo;
    private Integer   scanNo;
    private Integer   commentNo;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Boolean   status;
    private Integer   praiseNo;
    private Integer   treadNo;

    public TArticle() {}

    public TArticle(TArticle value) {
        this.id = value.id;
        this.title = value.title;
        this.summary = value.summary;
        this.author = value.author;
        this.source = value.source;
        this.sort = value.sort;
        this.clickNo = value.clickNo;
        this.scanNo = value.scanNo;
        this.commentNo = value.commentNo;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
        this.praiseNo = value.praiseNo;
        this.treadNo = value.treadNo;
    }

    public TArticle(
        Integer   id,
        String    title,
        String    summary,
        String    author,
        String    source,
        Integer   sort,
        Integer   clickNo,
        Integer   scanNo,
        Integer   commentNo,
        Timestamp createTime,
        Timestamp updateTime,
        Boolean   status,
        Integer   praiseNo,
        Integer   treadNo
    ) {
        this.id = id;
        this.title = title;
        this.summary = summary;
        this.author = author;
        this.source = source;
        this.sort = sort;
        this.clickNo = clickNo;
        this.scanNo = scanNo;
        this.commentNo = commentNo;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
        this.praiseNo = praiseNo;
        this.treadNo = treadNo;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getClickNo() {
        return this.clickNo;
    }

    public void setClickNo(Integer clickNo) {
        this.clickNo = clickNo;
    }

    public Integer getScanNo() {
        return this.scanNo;
    }

    public void setScanNo(Integer scanNo) {
        this.scanNo = scanNo;
    }

    public Integer getCommentNo() {
        return this.commentNo;
    }

    public void setCommentNo(Integer commentNo) {
        this.commentNo = commentNo;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getPraiseNo() {
        return this.praiseNo;
    }

    public void setPraiseNo(Integer praiseNo) {
        this.praiseNo = praiseNo;
    }

    public Integer getTreadNo() {
        return this.treadNo;
    }

    public void setTreadNo(Integer treadNo) {
        this.treadNo = treadNo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TArticle (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(summary);
        sb.append(", ").append(author);
        sb.append(", ").append(source);
        sb.append(", ").append(sort);
        sb.append(", ").append(clickNo);
        sb.append(", ").append(scanNo);
        sb.append(", ").append(commentNo);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);
        sb.append(", ").append(praiseNo);
        sb.append(", ").append(treadNo);

        sb.append(")");
        return sb.toString();
    }
}
