/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 文章内容表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArticleContent implements Serializable {

    private static final long serialVersionUID = 1289867458;

    private Integer   id;
    private Integer   articleId;
    private String    content;
    private Timestamp createTime;
    private Timestamp updateTime;

    public TArticleContent() {}

    public TArticleContent(TArticleContent value) {
        this.id = value.id;
        this.articleId = value.articleId;
        this.content = value.content;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TArticleContent(
        Integer   id,
        Integer   articleId,
        String    content,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.articleId = articleId;
        this.content = content;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TArticleContent (");

        sb.append(id);
        sb.append(", ").append(articleId);
        sb.append(", ").append(content);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
