/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 链接信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLink implements Serializable {

    private static final long serialVersionUID = -2083471693;

    private Integer   id;
    private String    url;
    private String    descri;
    private String    name;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Boolean   status;
    private String    image;

    public TLink() {}

    public TLink(TLink value) {
        this.id = value.id;
        this.url = value.url;
        this.descri = value.descri;
        this.name = value.name;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
        this.image = value.image;
    }

    public TLink(
        Integer   id,
        String    url,
        String    descri,
        String    name,
        Timestamp createTime,
        Timestamp updateTime,
        Boolean   status,
        String    image
    ) {
        this.id = id;
        this.url = url;
        this.descri = descri;
        this.name = name;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
        this.image = image;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescri() {
        return this.descri;
    }

    public void setDescri(String descri) {
        this.descri = descri;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TLink (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(descri);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);
        sb.append(", ").append(image);

        sb.append(")");
        return sb.toString();
    }
}
