/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 页面资源
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPage implements Serializable {

    private static final long serialVersionUID = -1436231892;

    private Integer   id;
    private String    url;
    private Integer   sort;
    private Integer   parentId;
    private Timestamp updateTime;
    private Timestamp createTime;
    private Boolean   status;
    private String    name;
    private String    describe;
    private Integer   type;

    public TPage() {}

    public TPage(TPage value) {
        this.id = value.id;
        this.url = value.url;
        this.sort = value.sort;
        this.parentId = value.parentId;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
        this.status = value.status;
        this.name = value.name;
        this.describe = value.describe;
        this.type = value.type;
    }

    public TPage(
        Integer   id,
        String    url,
        Integer   sort,
        Integer   parentId,
        Timestamp updateTime,
        Timestamp createTime,
        Boolean   status,
        String    name,
        String    describe,
        Integer   type
    ) {
        this.id = id;
        this.url = url;
        this.sort = sort;
        this.parentId = parentId;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.status = status;
        this.name = name;
        this.describe = describe;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescribe() {
        return this.describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TPage (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(sort);
        sb.append(", ").append(parentId);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(status);
        sb.append(", ").append(name);
        sb.append(", ").append(describe);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
