/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 回复
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReplay implements Serializable {

    private static final long serialVersionUID = -1307455889;

    private Integer   id;
    private Integer   commentId;
    private Integer   replayId;
    private String    replayHeadImg;
    private String    replayName;
    private String    content;
    private String    targetName;
    private Integer   targetId;
    private Timestamp createTime;
    private Boolean   status;

    public TReplay() {}

    public TReplay(TReplay value) {
        this.id = value.id;
        this.commentId = value.commentId;
        this.replayId = value.replayId;
        this.replayHeadImg = value.replayHeadImg;
        this.replayName = value.replayName;
        this.content = value.content;
        this.targetName = value.targetName;
        this.targetId = value.targetId;
        this.createTime = value.createTime;
        this.status = value.status;
    }

    public TReplay(
        Integer   id,
        Integer   commentId,
        Integer   replayId,
        String    replayHeadImg,
        String    replayName,
        String    content,
        String    targetName,
        Integer   targetId,
        Timestamp createTime,
        Boolean   status
    ) {
        this.id = id;
        this.commentId = commentId;
        this.replayId = replayId;
        this.replayHeadImg = replayHeadImg;
        this.replayName = replayName;
        this.content = content;
        this.targetName = targetName;
        this.targetId = targetId;
        this.createTime = createTime;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCommentId() {
        return this.commentId;
    }

    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public Integer getReplayId() {
        return this.replayId;
    }

    public void setReplayId(Integer replayId) {
        this.replayId = replayId;
    }

    public String getReplayHeadImg() {
        return this.replayHeadImg;
    }

    public void setReplayHeadImg(String replayHeadImg) {
        this.replayHeadImg = replayHeadImg;
    }

    public String getReplayName() {
        return this.replayName;
    }

    public void setReplayName(String replayName) {
        this.replayName = replayName;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTargetName() {
        return this.targetName;
    }

    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    public Integer getTargetId() {
        return this.targetId;
    }

    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TReplay (");

        sb.append(id);
        sb.append(", ").append(commentId);
        sb.append(", ").append(replayId);
        sb.append(", ").append(replayHeadImg);
        sb.append(", ").append(replayName);
        sb.append(", ").append(content);
        sb.append(", ").append(targetName);
        sb.append(", ").append(targetId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
