/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色资源表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleResource implements Serializable {

    private static final long serialVersionUID = -576676054;

    private Integer id;
    private Integer roleId;
    private Integer resourceId;

    public TRoleResource() {}

    public TRoleResource(TRoleResource value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.resourceId = value.resourceId;
    }

    public TRoleResource(
        Integer id,
        Integer roleId,
        Integer resourceId
    ) {
        this.id = id;
        this.roleId = roleId;
        this.resourceId = resourceId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoleResource (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(resourceId);

        sb.append(")");
        return sb.toString();
    }
}
