/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 标签
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTag implements Serializable {

    private static final long serialVersionUID = 114105478;

    private Integer   id;
    private String    name;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Boolean   status;
    private Integer   articleCount;
    private String    bgColor;
    private String    fontColor;

    public TTag() {}

    public TTag(TTag value) {
        this.id = value.id;
        this.name = value.name;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
        this.articleCount = value.articleCount;
        this.bgColor = value.bgColor;
        this.fontColor = value.fontColor;
    }

    public TTag(
        Integer   id,
        String    name,
        Timestamp createTime,
        Timestamp updateTime,
        Boolean   status,
        Integer   articleCount,
        String    bgColor,
        String    fontColor
    ) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
        this.articleCount = articleCount;
        this.bgColor = bgColor;
        this.fontColor = fontColor;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getArticleCount() {
        return this.articleCount;
    }

    public void setArticleCount(Integer articleCount) {
        this.articleCount = articleCount;
    }

    public String getBgColor() {
        return this.bgColor;
    }

    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }

    public String getFontColor() {
        return this.fontColor;
    }

    public void setFontColor(String fontColor) {
        this.fontColor = fontColor;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTag (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);
        sb.append(", ").append(articleCount);
        sb.append(", ").append(bgColor);
        sb.append(", ").append(fontColor);

        sb.append(")");
        return sb.toString();
    }
}
