/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 1274952596;

    private Integer   id;
    private String    nickname;
    private String    headPic;
    private Timestamp createTime;
    private String    email;
    private Timestamp updateTime;
    private Boolean   status;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.nickname = value.nickname;
        this.headPic = value.headPic;
        this.createTime = value.createTime;
        this.email = value.email;
        this.updateTime = value.updateTime;
        this.status = value.status;
    }

    public TUser(
        Integer   id,
        String    nickname,
        String    headPic,
        Timestamp createTime,
        String    email,
        Timestamp updateTime,
        Boolean   status
    ) {
        this.id = id;
        this.nickname = nickname;
        this.headPic = headPic;
        this.createTime = createTime;
        this.email = email;
        this.updateTime = updateTime;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getHeadPic() {
        return this.headPic;
    }

    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(nickname);
        sb.append(", ").append(headPic);
        sb.append(", ").append(createTime);
        sb.append(", ").append(email);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
