server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lemon?useUnicode=true&amp&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: 12345678
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
  devtools:
    restart:
      additional-paths: src/main
      enabled: true
  freemarker:
    cache: false
    template-loader-path: ["classpath:/static/"]
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: top.joylife.lemon.dao.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  mappers: top.joylife.lemon.dao.mapper
  identity: MYSQL

# 系统自定义参数
lemon:
  theme: default

