/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import top.joylife.lemon.jooq.tables.TAccount;
import top.joylife.lemon.jooq.tables.TArticle;
import top.joylife.lemon.jooq.tables.TArticleContent;
import top.joylife.lemon.jooq.tables.TArticleTag;
import top.joylife.lemon.jooq.tables.TComment;
import top.joylife.lemon.jooq.tables.TLink;
import top.joylife.lemon.jooq.tables.TPage;
import top.joylife.lemon.jooq.tables.TProperties;
import top.joylife.lemon.jooq.tables.TReplay;
import top.joylife.lemon.jooq.tables.TResource;
import top.joylife.lemon.jooq.tables.TRole;
import top.joylife.lemon.jooq.tables.TRoleResource;
import top.joylife.lemon.jooq.tables.TTag;
import top.joylife.lemon.jooq.tables.TUser;
import top.joylife.lemon.jooq.tables.TUserRole;
import top.joylife.lemon.jooq.tables.records.TAccountRecord;
import top.joylife.lemon.jooq.tables.records.TArticleContentRecord;
import top.joylife.lemon.jooq.tables.records.TArticleRecord;
import top.joylife.lemon.jooq.tables.records.TArticleTagRecord;
import top.joylife.lemon.jooq.tables.records.TCommentRecord;
import top.joylife.lemon.jooq.tables.records.TLinkRecord;
import top.joylife.lemon.jooq.tables.records.TPageRecord;
import top.joylife.lemon.jooq.tables.records.TPropertiesRecord;
import top.joylife.lemon.jooq.tables.records.TReplayRecord;
import top.joylife.lemon.jooq.tables.records.TResourceRecord;
import top.joylife.lemon.jooq.tables.records.TRoleRecord;
import top.joylife.lemon.jooq.tables.records.TRoleResourceRecord;
import top.joylife.lemon.jooq.tables.records.TTagRecord;
import top.joylife.lemon.jooq.tables.records.TUserRecord;
import top.joylife.lemon.jooq.tables.records.TUserRoleRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>lemon</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TAccountRecord, Integer> IDENTITY_T_ACCOUNT = Identities0.IDENTITY_T_ACCOUNT;
    public static final Identity<TArticleRecord, Integer> IDENTITY_T_ARTICLE = Identities0.IDENTITY_T_ARTICLE;
    public static final Identity<TArticleContentRecord, Integer> IDENTITY_T_ARTICLE_CONTENT = Identities0.IDENTITY_T_ARTICLE_CONTENT;
    public static final Identity<TArticleTagRecord, Integer> IDENTITY_T_ARTICLE_TAG = Identities0.IDENTITY_T_ARTICLE_TAG;
    public static final Identity<TCommentRecord, Integer> IDENTITY_T_COMMENT = Identities0.IDENTITY_T_COMMENT;
    public static final Identity<TLinkRecord, Integer> IDENTITY_T_LINK = Identities0.IDENTITY_T_LINK;
    public static final Identity<TPageRecord, Integer> IDENTITY_T_PAGE = Identities0.IDENTITY_T_PAGE;
    public static final Identity<TPropertiesRecord, Integer> IDENTITY_T_PROPERTIES = Identities0.IDENTITY_T_PROPERTIES;
    public static final Identity<TReplayRecord, Integer> IDENTITY_T_REPLAY = Identities0.IDENTITY_T_REPLAY;
    public static final Identity<TResourceRecord, Integer> IDENTITY_T_RESOURCE = Identities0.IDENTITY_T_RESOURCE;
    public static final Identity<TRoleRecord, Integer> IDENTITY_T_ROLE = Identities0.IDENTITY_T_ROLE;
    public static final Identity<TRoleResourceRecord, Integer> IDENTITY_T_ROLE_RESOURCE = Identities0.IDENTITY_T_ROLE_RESOURCE;
    public static final Identity<TTagRecord, Integer> IDENTITY_T_TAG = Identities0.IDENTITY_T_TAG;
    public static final Identity<TUserRecord, Integer> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;
    public static final Identity<TUserRoleRecord, Integer> IDENTITY_T_USER_ROLE = Identities0.IDENTITY_T_USER_ROLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TAccountRecord> KEY_T_ACCOUNT_PRIMARY = UniqueKeys0.KEY_T_ACCOUNT_PRIMARY;
    public static final UniqueKey<TArticleRecord> KEY_T_ARTICLE_PRIMARY = UniqueKeys0.KEY_T_ARTICLE_PRIMARY;
    public static final UniqueKey<TArticleContentRecord> KEY_T_ARTICLE_CONTENT_PRIMARY = UniqueKeys0.KEY_T_ARTICLE_CONTENT_PRIMARY;
    public static final UniqueKey<TArticleTagRecord> KEY_T_ARTICLE_TAG_PRIMARY = UniqueKeys0.KEY_T_ARTICLE_TAG_PRIMARY;
    public static final UniqueKey<TCommentRecord> KEY_T_COMMENT_PRIMARY = UniqueKeys0.KEY_T_COMMENT_PRIMARY;
    public static final UniqueKey<TLinkRecord> KEY_T_LINK_PRIMARY = UniqueKeys0.KEY_T_LINK_PRIMARY;
    public static final UniqueKey<TPageRecord> KEY_T_PAGE_PRIMARY = UniqueKeys0.KEY_T_PAGE_PRIMARY;
    public static final UniqueKey<TPropertiesRecord> KEY_T_PROPERTIES_PRIMARY = UniqueKeys0.KEY_T_PROPERTIES_PRIMARY;
    public static final UniqueKey<TReplayRecord> KEY_T_REPLAY_PRIMARY = UniqueKeys0.KEY_T_REPLAY_PRIMARY;
    public static final UniqueKey<TResourceRecord> KEY_T_RESOURCE_PRIMARY = UniqueKeys0.KEY_T_RESOURCE_PRIMARY;
    public static final UniqueKey<TRoleRecord> KEY_T_ROLE_PRIMARY = UniqueKeys0.KEY_T_ROLE_PRIMARY;
    public static final UniqueKey<TRoleResourceRecord> KEY_T_ROLE_RESOURCE_PRIMARY = UniqueKeys0.KEY_T_ROLE_RESOURCE_PRIMARY;
    public static final UniqueKey<TTagRecord> KEY_T_TAG_PRIMARY = UniqueKeys0.KEY_T_TAG_PRIMARY;
    public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;
    public static final UniqueKey<TUserRoleRecord> KEY_T_USER_ROLE_PRIMARY = UniqueKeys0.KEY_T_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TAccountRecord, Integer> IDENTITY_T_ACCOUNT = createIdentity(TAccount.T_ACCOUNT, TAccount.T_ACCOUNT.ID);
        public static Identity<TArticleRecord, Integer> IDENTITY_T_ARTICLE = createIdentity(TArticle.T_ARTICLE, TArticle.T_ARTICLE.ID);
        public static Identity<TArticleContentRecord, Integer> IDENTITY_T_ARTICLE_CONTENT = createIdentity(TArticleContent.T_ARTICLE_CONTENT, TArticleContent.T_ARTICLE_CONTENT.ID);
        public static Identity<TArticleTagRecord, Integer> IDENTITY_T_ARTICLE_TAG = createIdentity(TArticleTag.T_ARTICLE_TAG, TArticleTag.T_ARTICLE_TAG.ID);
        public static Identity<TCommentRecord, Integer> IDENTITY_T_COMMENT = createIdentity(TComment.T_COMMENT, TComment.T_COMMENT.ID);
        public static Identity<TLinkRecord, Integer> IDENTITY_T_LINK = createIdentity(TLink.T_LINK, TLink.T_LINK.ID);
        public static Identity<TPageRecord, Integer> IDENTITY_T_PAGE = createIdentity(TPage.T_PAGE, TPage.T_PAGE.ID);
        public static Identity<TPropertiesRecord, Integer> IDENTITY_T_PROPERTIES = createIdentity(TProperties.T_PROPERTIES, TProperties.T_PROPERTIES.ID);
        public static Identity<TReplayRecord, Integer> IDENTITY_T_REPLAY = createIdentity(TReplay.T_REPLAY, TReplay.T_REPLAY.ID);
        public static Identity<TResourceRecord, Integer> IDENTITY_T_RESOURCE = createIdentity(TResource.T_RESOURCE, TResource.T_RESOURCE.ID);
        public static Identity<TRoleRecord, Integer> IDENTITY_T_ROLE = createIdentity(TRole.T_ROLE, TRole.T_ROLE.ID);
        public static Identity<TRoleResourceRecord, Integer> IDENTITY_T_ROLE_RESOURCE = createIdentity(TRoleResource.T_ROLE_RESOURCE, TRoleResource.T_ROLE_RESOURCE.ID);
        public static Identity<TTagRecord, Integer> IDENTITY_T_TAG = createIdentity(TTag.T_TAG, TTag.T_TAG.ID);
        public static Identity<TUserRecord, Integer> IDENTITY_T_USER = createIdentity(TUser.T_USER, TUser.T_USER.ID);
        public static Identity<TUserRoleRecord, Integer> IDENTITY_T_USER_ROLE = createIdentity(TUserRole.T_USER_ROLE, TUserRole.T_USER_ROLE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TAccountRecord> KEY_T_ACCOUNT_PRIMARY = createUniqueKey(TAccount.T_ACCOUNT, "KEY_t_account_PRIMARY", TAccount.T_ACCOUNT.ID);
        public static final UniqueKey<TArticleRecord> KEY_T_ARTICLE_PRIMARY = createUniqueKey(TArticle.T_ARTICLE, "KEY_t_article_PRIMARY", TArticle.T_ARTICLE.ID);
        public static final UniqueKey<TArticleContentRecord> KEY_T_ARTICLE_CONTENT_PRIMARY = createUniqueKey(TArticleContent.T_ARTICLE_CONTENT, "KEY_t_article_content_PRIMARY", TArticleContent.T_ARTICLE_CONTENT.ID);
        public static final UniqueKey<TArticleTagRecord> KEY_T_ARTICLE_TAG_PRIMARY = createUniqueKey(TArticleTag.T_ARTICLE_TAG, "KEY_t_article_tag_PRIMARY", TArticleTag.T_ARTICLE_TAG.ID);
        public static final UniqueKey<TCommentRecord> KEY_T_COMMENT_PRIMARY = createUniqueKey(TComment.T_COMMENT, "KEY_t_comment_PRIMARY", TComment.T_COMMENT.ID);
        public static final UniqueKey<TLinkRecord> KEY_T_LINK_PRIMARY = createUniqueKey(TLink.T_LINK, "KEY_t_link_PRIMARY", TLink.T_LINK.ID);
        public static final UniqueKey<TPageRecord> KEY_T_PAGE_PRIMARY = createUniqueKey(TPage.T_PAGE, "KEY_t_page_PRIMARY", TPage.T_PAGE.ID);
        public static final UniqueKey<TPropertiesRecord> KEY_T_PROPERTIES_PRIMARY = createUniqueKey(TProperties.T_PROPERTIES, "KEY_t_properties_PRIMARY", TProperties.T_PROPERTIES.ID);
        public static final UniqueKey<TReplayRecord> KEY_T_REPLAY_PRIMARY = createUniqueKey(TReplay.T_REPLAY, "KEY_t_replay_PRIMARY", TReplay.T_REPLAY.ID);
        public static final UniqueKey<TResourceRecord> KEY_T_RESOURCE_PRIMARY = createUniqueKey(TResource.T_RESOURCE, "KEY_t_resource_PRIMARY", TResource.T_RESOURCE.ID);
        public static final UniqueKey<TRoleRecord> KEY_T_ROLE_PRIMARY = createUniqueKey(TRole.T_ROLE, "KEY_t_role_PRIMARY", TRole.T_ROLE.ID);
        public static final UniqueKey<TRoleResourceRecord> KEY_T_ROLE_RESOURCE_PRIMARY = createUniqueKey(TRoleResource.T_ROLE_RESOURCE, "KEY_t_role_resource_PRIMARY", TRoleResource.T_ROLE_RESOURCE.ID);
        public static final UniqueKey<TTagRecord> KEY_T_TAG_PRIMARY = createUniqueKey(TTag.T_TAG, "KEY_t_tag_PRIMARY", TTag.T_TAG.ID);
        public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = createUniqueKey(TUser.T_USER, "KEY_t_user_PRIMARY", TUser.T_USER.ID);
        public static final UniqueKey<TUserRoleRecord> KEY_T_USER_ROLE_PRIMARY = createUniqueKey(TUserRole.T_USER_ROLE, "KEY_t_user_role_PRIMARY", TUserRole.T_USER_ROLE.ID);
    }
}
