/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import top.joylife.lemon.jooq.tables.TAccount;
import top.joylife.lemon.jooq.tables.TArticle;
import top.joylife.lemon.jooq.tables.TArticleContent;
import top.joylife.lemon.jooq.tables.TArticleTag;
import top.joylife.lemon.jooq.tables.TComment;
import top.joylife.lemon.jooq.tables.TLink;
import top.joylife.lemon.jooq.tables.TPage;
import top.joylife.lemon.jooq.tables.TProperties;
import top.joylife.lemon.jooq.tables.TReplay;
import top.joylife.lemon.jooq.tables.TResource;
import top.joylife.lemon.jooq.tables.TRole;
import top.joylife.lemon.jooq.tables.TRoleResource;
import top.joylife.lemon.jooq.tables.TTag;
import top.joylife.lemon.jooq.tables.TUser;
import top.joylife.lemon.jooq.tables.TUserRole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lemon extends SchemaImpl {

    private static final long serialVersionUID = -1612981614;

    /**
     * The reference instance of <code>lemon</code>
     */
    public static final Lemon LEMON = new Lemon();

    /**
     * 用户账号信息
     */
    public final TAccount T_ACCOUNT = top.joylife.lemon.jooq.tables.TAccount.T_ACCOUNT;

    /**
     * 文章表
     */
    public final TArticle T_ARTICLE = top.joylife.lemon.jooq.tables.TArticle.T_ARTICLE;

    /**
     * 文章内容表
     */
    public final TArticleContent T_ARTICLE_CONTENT = top.joylife.lemon.jooq.tables.TArticleContent.T_ARTICLE_CONTENT;

    /**
     * 文章标签关联表
     */
    public final TArticleTag T_ARTICLE_TAG = top.joylife.lemon.jooq.tables.TArticleTag.T_ARTICLE_TAG;

    /**
     * 评论
     */
    public final TComment T_COMMENT = top.joylife.lemon.jooq.tables.TComment.T_COMMENT;

    /**
     * 链接信息表
     */
    public final TLink T_LINK = top.joylife.lemon.jooq.tables.TLink.T_LINK;

    /**
     * 页面资源
     */
    public final TPage T_PAGE = top.joylife.lemon.jooq.tables.TPage.T_PAGE;

    /**
     * The table <code>lemon.t_properties</code>.
     */
    public final TProperties T_PROPERTIES = top.joylife.lemon.jooq.tables.TProperties.T_PROPERTIES;

    /**
     * 回复
     */
    public final TReplay T_REPLAY = top.joylife.lemon.jooq.tables.TReplay.T_REPLAY;

    /**
     * 资源表
     */
    public final TResource T_RESOURCE = top.joylife.lemon.jooq.tables.TResource.T_RESOURCE;

    /**
     * 角色表
     */
    public final TRole T_ROLE = top.joylife.lemon.jooq.tables.TRole.T_ROLE;

    /**
     * 角色资源表
     */
    public final TRoleResource T_ROLE_RESOURCE = top.joylife.lemon.jooq.tables.TRoleResource.T_ROLE_RESOURCE;

    /**
     * 标签
     */
    public final TTag T_TAG = top.joylife.lemon.jooq.tables.TTag.T_TAG;

    /**
     * 用户信息表
     */
    public final TUser T_USER = top.joylife.lemon.jooq.tables.TUser.T_USER;

    /**
     * 用户角色关联
     */
    public final TUserRole T_USER_ROLE = top.joylife.lemon.jooq.tables.TUserRole.T_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Lemon() {
        super("lemon", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAccount.T_ACCOUNT,
            TArticle.T_ARTICLE,
            TArticleContent.T_ARTICLE_CONTENT,
            TArticleTag.T_ARTICLE_TAG,
            TComment.T_COMMENT,
            TLink.T_LINK,
            TPage.T_PAGE,
            TProperties.T_PROPERTIES,
            TReplay.T_REPLAY,
            TResource.T_RESOURCE,
            TRole.T_ROLE,
            TRoleResource.T_ROLE_RESOURCE,
            TTag.T_TAG,
            TUser.T_USER,
            TUserRole.T_USER_ROLE);
    }
}
