/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq;


import javax.annotation.Generated;

import top.joylife.lemon.jooq.tables.TAccount;
import top.joylife.lemon.jooq.tables.TArticle;
import top.joylife.lemon.jooq.tables.TArticleContent;
import top.joylife.lemon.jooq.tables.TArticleTag;
import top.joylife.lemon.jooq.tables.TComment;
import top.joylife.lemon.jooq.tables.TLink;
import top.joylife.lemon.jooq.tables.TPage;
import top.joylife.lemon.jooq.tables.TProperties;
import top.joylife.lemon.jooq.tables.TReplay;
import top.joylife.lemon.jooq.tables.TResource;
import top.joylife.lemon.jooq.tables.TRole;
import top.joylife.lemon.jooq.tables.TRoleResource;
import top.joylife.lemon.jooq.tables.TTag;
import top.joylife.lemon.jooq.tables.TUser;
import top.joylife.lemon.jooq.tables.TUserRole;


/**
 * Convenience access to all tables in lemon
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户账号信息
     */
    public static final TAccount T_ACCOUNT = top.joylife.lemon.jooq.tables.TAccount.T_ACCOUNT;

    /**
     * 文章表
     */
    public static final TArticle T_ARTICLE = top.joylife.lemon.jooq.tables.TArticle.T_ARTICLE;

    /**
     * 文章内容表
     */
    public static final TArticleContent T_ARTICLE_CONTENT = top.joylife.lemon.jooq.tables.TArticleContent.T_ARTICLE_CONTENT;

    /**
     * 文章标签关联表
     */
    public static final TArticleTag T_ARTICLE_TAG = top.joylife.lemon.jooq.tables.TArticleTag.T_ARTICLE_TAG;

    /**
     * 评论
     */
    public static final TComment T_COMMENT = top.joylife.lemon.jooq.tables.TComment.T_COMMENT;

    /**
     * 链接信息表
     */
    public static final TLink T_LINK = top.joylife.lemon.jooq.tables.TLink.T_LINK;

    /**
     * 页面资源
     */
    public static final TPage T_PAGE = top.joylife.lemon.jooq.tables.TPage.T_PAGE;

    /**
     * The table <code>lemon.t_properties</code>.
     */
    public static final TProperties T_PROPERTIES = top.joylife.lemon.jooq.tables.TProperties.T_PROPERTIES;

    /**
     * 回复
     */
    public static final TReplay T_REPLAY = top.joylife.lemon.jooq.tables.TReplay.T_REPLAY;

    /**
     * 资源表
     */
    public static final TResource T_RESOURCE = top.joylife.lemon.jooq.tables.TResource.T_RESOURCE;

    /**
     * 角色表
     */
    public static final TRole T_ROLE = top.joylife.lemon.jooq.tables.TRole.T_ROLE;

    /**
     * 角色资源表
     */
    public static final TRoleResource T_ROLE_RESOURCE = top.joylife.lemon.jooq.tables.TRoleResource.T_ROLE_RESOURCE;

    /**
     * 标签
     */
    public static final TTag T_TAG = top.joylife.lemon.jooq.tables.TTag.T_TAG;

    /**
     * 用户信息表
     */
    public static final TUser T_USER = top.joylife.lemon.jooq.tables.TUser.T_USER;

    /**
     * 用户角色关联
     */
    public static final TUserRole T_USER_ROLE = top.joylife.lemon.jooq.tables.TUserRole.T_USER_ROLE;
}
