/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TArticleTag;


/**
 * 文章标签关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArticleTagRecord extends UpdatableRecordImpl<TArticleTagRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1937630327;

    /**
     * Setter for <code>lemon.t_article_tag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_article_tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_article_tag.article_id</code>.
     */
    public void setArticleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_article_tag.article_id</code>.
     */
    public Integer getArticleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lemon.t_article_tag.tag_id</code>.
     */
    public void setTagId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_article_tag.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TArticleTag.T_ARTICLE_TAG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TArticleTag.T_ARTICLE_TAG.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TArticleTag.T_ARTICLE_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleTagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleTagRecord value2(Integer value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleTagRecord value3(Integer value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleTagRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TArticleTagRecord
     */
    public TArticleTagRecord() {
        super(TArticleTag.T_ARTICLE_TAG);
    }

    /**
     * Create a detached, initialised TArticleTagRecord
     */
    public TArticleTagRecord(Integer id, Integer articleId, Integer tagId) {
        super(TArticleTag.T_ARTICLE_TAG);

        set(0, id);
        set(1, articleId);
        set(2, tagId);
    }
}
