/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TArticle;


/**
 * 文章表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArticleRecord extends UpdatableRecordImpl<TArticleRecord> implements Record14<Integer, String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 975182390;

    /**
     * Setter for <code>lemon.t_article.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_article.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_article.title</code>. 标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_article.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lemon.t_article.summary</code>. 摘要
     */
    public void setSummary(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_article.summary</code>. 摘要
     */
    public String getSummary() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lemon.t_article.author</code>. 作者
     */
    public void setAuthor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lemon.t_article.author</code>. 作者
     */
    public String getAuthor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lemon.t_article.source</code>. 文章来源
     */
    public void setSource(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lemon.t_article.source</code>. 文章来源
     */
    public String getSource() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lemon.t_article.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lemon.t_article.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lemon.t_article.click_no</code>. 点击数
     */
    public void setClickNo(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lemon.t_article.click_no</code>. 点击数
     */
    public Integer getClickNo() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>lemon.t_article.scan_no</code>. 浏览数
     */
    public void setScanNo(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lemon.t_article.scan_no</code>. 浏览数
     */
    public Integer getScanNo() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lemon.t_article.comment_no</code>. 评论数
     */
    public void setCommentNo(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>lemon.t_article.comment_no</code>. 评论数
     */
    public Integer getCommentNo() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>lemon.t_article.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>lemon.t_article.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>lemon.t_article.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>lemon.t_article.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>lemon.t_article.status</code>. 状态标识,0-正常，1-删除
     */
    public void setStatus(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>lemon.t_article.status</code>. 状态标识,0-正常，1-删除
     */
    public Boolean getStatus() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>lemon.t_article.praise_no</code>.
     */
    public void setPraiseNo(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>lemon.t_article.praise_no</code>.
     */
    public Integer getPraiseNo() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>lemon.t_article.tread_no</code>.
     */
    public void setTreadNo(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>lemon.t_article.tread_no</code>.
     */
    public Integer getTreadNo() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Boolean, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Boolean, Integer, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TArticle.T_ARTICLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TArticle.T_ARTICLE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TArticle.T_ARTICLE.SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TArticle.T_ARTICLE.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TArticle.T_ARTICLE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TArticle.T_ARTICLE.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TArticle.T_ARTICLE.CLICK_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TArticle.T_ARTICLE.SCAN_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TArticle.T_ARTICLE.COMMENT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TArticle.T_ARTICLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TArticle.T_ARTICLE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return TArticle.T_ARTICLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return TArticle.T_ARTICLE.PRAISE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TArticle.T_ARTICLE.TREAD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSummary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getClickNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getScanNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCommentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getPraiseNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getTreadNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value3(String value) {
        setSummary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value4(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value5(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value6(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value7(Integer value) {
        setClickNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value8(Integer value) {
        setScanNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value9(Integer value) {
        setCommentNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value12(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value13(Integer value) {
        setPraiseNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord value14(Integer value) {
        setTreadNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TArticleRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, Integer value8, Integer value9, Timestamp value10, Timestamp value11, Boolean value12, Integer value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TArticleRecord
     */
    public TArticleRecord() {
        super(TArticle.T_ARTICLE);
    }

    /**
     * Create a detached, initialised TArticleRecord
     */
    public TArticleRecord(Integer id, String title, String summary, String author, String source, Integer sort, Integer clickNo, Integer scanNo, Integer commentNo, Timestamp createTime, Timestamp updateTime, Boolean status, Integer praiseNo, Integer treadNo) {
        super(TArticle.T_ARTICLE);

        set(0, id);
        set(1, title);
        set(2, summary);
        set(3, author);
        set(4, source);
        set(5, sort);
        set(6, clickNo);
        set(7, scanNo);
        set(8, commentNo);
        set(9, createTime);
        set(10, updateTime);
        set(11, status);
        set(12, praiseNo);
        set(13, treadNo);
    }
}
