/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TComment;


/**
 * 评论
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCommentRecord extends UpdatableRecordImpl<TCommentRecord> implements Record9<Integer, Integer, Integer, String, Timestamp, Boolean, Boolean, String, String> {

    private static final long serialVersionUID = -2097133339;

    /**
     * Setter for <code>lemon.t_comment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_comment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_comment.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_comment.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lemon.t_comment.article_id</code>. 文章id
     */
    public void setArticleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_comment.article_id</code>. 文章id
     */
    public Integer getArticleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lemon.t_comment.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lemon.t_comment.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lemon.t_comment.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>lemon.t_comment.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>lemon.t_comment.delete_flag</code>.
     */
    public void setDeleteFlag(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>lemon.t_comment.delete_flag</code>.
     */
    public Boolean getDeleteFlag() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>lemon.t_comment.status</code>.
     */
    public void setStatus(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>lemon.t_comment.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>lemon.t_comment.user_head_img</code>. 用户头像
     */
    public void setUserHeadImg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lemon.t_comment.user_head_img</code>. 用户头像
     */
    public String getUserHeadImg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>lemon.t_comment.user_name</code>. 用户名
     */
    public void setUserName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>lemon.t_comment.user_name</code>. 用户名
     */
    public String getUserName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Timestamp, Boolean, Boolean, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Timestamp, Boolean, Boolean, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TComment.T_COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TComment.T_COMMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TComment.T_COMMENT.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TComment.T_COMMENT.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TComment.T_COMMENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TComment.T_COMMENT.DELETE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TComment.T_COMMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TComment.T_COMMENT.USER_HEAD_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TComment.T_COMMENT.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDeleteFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserHeadImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value3(Integer value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value6(Boolean value) {
        setDeleteFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value7(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value8(String value) {
        setUserHeadImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord value9(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCommentRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5, Boolean value6, Boolean value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCommentRecord
     */
    public TCommentRecord() {
        super(TComment.T_COMMENT);
    }

    /**
     * Create a detached, initialised TCommentRecord
     */
    public TCommentRecord(Integer id, Integer userId, Integer articleId, String content, Timestamp createTime, Boolean deleteFlag, Boolean status, String userHeadImg, String userName) {
        super(TComment.T_COMMENT);

        set(0, id);
        set(1, userId);
        set(2, articleId);
        set(3, content);
        set(4, createTime);
        set(5, deleteFlag);
        set(6, status);
        set(7, userHeadImg);
        set(8, userName);
    }
}
