/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TLink;


/**
 * 链接信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLinkRecord extends UpdatableRecordImpl<TLinkRecord> implements Record8<Integer, String, String, String, Timestamp, Timestamp, Boolean, String> {

    private static final long serialVersionUID = -916081058;

    /**
     * Setter for <code>lemon.t_link.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_link.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_link.url</code>. url
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_link.url</code>. url
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lemon.t_link.descri</code>. 连接描述
     */
    public void setDescri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_link.descri</code>. 连接描述
     */
    public String getDescri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lemon.t_link.name</code>. 连接名字
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lemon.t_link.name</code>. 连接名字
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lemon.t_link.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>lemon.t_link.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>lemon.t_link.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>lemon.t_link.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>lemon.t_link.status</code>. 状态标识，0-未删除，1-删除
     */
    public void setStatus(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>lemon.t_link.status</code>. 状态标识，0-未删除，1-删除
     */
    public Boolean getStatus() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>lemon.t_link.image</code>. 图片
     */
    public void setImage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lemon.t_link.image</code>. 图片
     */
    public String getImage() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Timestamp, Boolean, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Timestamp, Boolean, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TLink.T_LINK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TLink.T_LINK.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TLink.T_LINK.DESCRI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TLink.T_LINK.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TLink.T_LINK.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TLink.T_LINK.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TLink.T_LINK.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TLink.T_LINK.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value3(String value) {
        setDescri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value7(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord value8(String value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLinkRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, Boolean value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLinkRecord
     */
    public TLinkRecord() {
        super(TLink.T_LINK);
    }

    /**
     * Create a detached, initialised TLinkRecord
     */
    public TLinkRecord(Integer id, String url, String descri, String name, Timestamp createTime, Timestamp updateTime, Boolean status, String image) {
        super(TLink.T_LINK);

        set(0, id);
        set(1, url);
        set(2, descri);
        set(3, name);
        set(4, createTime);
        set(5, updateTime);
        set(6, status);
        set(7, image);
    }
}
