/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TReplay;


/**
 * 回复
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReplayRecord extends UpdatableRecordImpl<TReplayRecord> implements Record10<Integer, Integer, Integer, String, String, String, String, Integer, Timestamp, Boolean> {

    private static final long serialVersionUID = -1221449041;

    /**
     * Setter for <code>lemon.t_replay.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_replay.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_replay.comment_id</code>. 评论id
     */
    public void setCommentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_replay.comment_id</code>. 评论id
     */
    public Integer getCommentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lemon.t_replay.replay_id</code>. 回复人id
     */
    public void setReplayId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_replay.replay_id</code>. 回复人id
     */
    public Integer getReplayId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lemon.t_replay.replay_head_img</code>. 用户头像
     */
    public void setReplayHeadImg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lemon.t_replay.replay_head_img</code>. 用户头像
     */
    public String getReplayHeadImg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lemon.t_replay.replay_name</code>. 用户名
     */
    public void setReplayName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lemon.t_replay.replay_name</code>. 用户名
     */
    public String getReplayName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lemon.t_replay.content</code>. 回复内容
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lemon.t_replay.content</code>. 回复内容
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lemon.t_replay.target_name</code>. 评论目标名字
     */
    public void setTargetName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lemon.t_replay.target_name</code>. 评论目标名字
     */
    public String getTargetName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lemon.t_replay.target_id</code>. 评论目标id
     */
    public void setTargetId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lemon.t_replay.target_id</code>. 评论目标id
     */
    public Integer getTargetId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lemon.t_replay.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>lemon.t_replay.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>lemon.t_replay.status</code>. 评论状态
     */
    public void setStatus(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>lemon.t_replay.status</code>. 评论状态
     */
    public Boolean getStatus() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, String, Integer, Timestamp, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, String, Integer, Timestamp, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TReplay.T_REPLAY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TReplay.T_REPLAY.COMMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TReplay.T_REPLAY.REPLAY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TReplay.T_REPLAY.REPLAY_HEAD_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TReplay.T_REPLAY.REPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TReplay.T_REPLAY.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TReplay.T_REPLAY.TARGET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TReplay.T_REPLAY.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TReplay.T_REPLAY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return TReplay.T_REPLAY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCommentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getReplayId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReplayHeadImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTargetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value2(Integer value) {
        setCommentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value3(Integer value) {
        setReplayId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value4(String value) {
        setReplayHeadImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value5(String value) {
        setReplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value7(String value) {
        setTargetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value8(Integer value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord value10(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplayRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, Integer value8, Timestamp value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TReplayRecord
     */
    public TReplayRecord() {
        super(TReplay.T_REPLAY);
    }

    /**
     * Create a detached, initialised TReplayRecord
     */
    public TReplayRecord(Integer id, Integer commentId, Integer replayId, String replayHeadImg, String replayName, String content, String targetName, Integer targetId, Timestamp createTime, Boolean status) {
        super(TReplay.T_REPLAY);

        set(0, id);
        set(1, commentId);
        set(2, replayId);
        set(3, replayHeadImg);
        set(4, replayName);
        set(5, content);
        set(6, targetName);
        set(7, targetId);
        set(8, createTime);
        set(9, status);
    }
}
