/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TRoleResource;


/**
 * 角色资源表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleResourceRecord extends UpdatableRecordImpl<TRoleResourceRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1596168532;

    /**
     * Setter for <code>lemon.t_role_resource.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_role_resource.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_role_resource.role_id</code>. 角色id
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_role_resource.role_id</code>. 角色id
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>lemon.t_role_resource.resource_id</code>. 资源id
     */
    public void setResourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_role_resource.resource_id</code>. 资源id
     */
    public Integer getResourceId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TRoleResource.T_ROLE_RESOURCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TRoleResource.T_ROLE_RESOURCE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TRoleResource.T_ROLE_RESOURCE.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleResourceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleResourceRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleResourceRecord value3(Integer value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleResourceRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoleResourceRecord
     */
    public TRoleResourceRecord() {
        super(TRoleResource.T_ROLE_RESOURCE);
    }

    /**
     * Create a detached, initialised TRoleResourceRecord
     */
    public TRoleResourceRecord(Integer id, Integer roleId, Integer resourceId) {
        super(TRoleResource.T_ROLE_RESOURCE);

        set(0, id);
        set(1, roleId);
        set(2, resourceId);
    }
}
