/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import top.joylife.lemon.jooq.tables.TTag;


/**
 * 标签
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTagRecord extends UpdatableRecordImpl<TTagRecord> implements Record8<Integer, String, Timestamp, Timestamp, Boolean, Integer, String, String> {

    private static final long serialVersionUID = -208538749;

    /**
     * Setter for <code>lemon.t_tag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lemon.t_tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lemon.t_tag.name</code>. 名字
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lemon.t_tag.name</code>. 名字
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lemon.t_tag.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>lemon.t_tag.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>lemon.t_tag.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>lemon.t_tag.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>lemon.t_tag.status</code>. 状态标识,0-正常,1-删除
     */
    public void setStatus(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>lemon.t_tag.status</code>. 状态标识,0-正常,1-删除
     */
    public Boolean getStatus() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>lemon.t_tag.article_count</code>.
     */
    public void setArticleCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lemon.t_tag.article_count</code>.
     */
    public Integer getArticleCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lemon.t_tag.bg_color</code>.
     */
    public void setBgColor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lemon.t_tag.bg_color</code>.
     */
    public String getBgColor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lemon.t_tag.font_color</code>.
     */
    public void setFontColor(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lemon.t_tag.font_color</code>.
     */
    public String getFontColor() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, Boolean, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, Boolean, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TTag.T_TAG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TTag.T_TAG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TTag.T_TAG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TTag.T_TAG.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return TTag.T_TAG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TTag.T_TAG.ARTICLE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TTag.T_TAG.BG_COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TTag.T_TAG.FONT_COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getArticleCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBgColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFontColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value3(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value5(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value6(Integer value) {
        setArticleCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value7(String value) {
        setBgColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord value8(String value) {
        setFontColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTagRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, Boolean value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTagRecord
     */
    public TTagRecord() {
        super(TTag.T_TAG);
    }

    /**
     * Create a detached, initialised TTagRecord
     */
    public TTagRecord(Integer id, String name, Timestamp createTime, Timestamp updateTime, Boolean status, Integer articleCount, String bgColor, String fontColor) {
        super(TTag.T_TAG);

        set(0, id);
        set(1, name);
        set(2, createTime);
        set(3, updateTime);
        set(4, status);
        set(5, articleCount);
        set(6, bgColor);
        set(7, fontColor);
    }
}
