/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.joylife.lemon.jooq.Keys;
import top.joylife.lemon.jooq.Lemon;
import top.joylife.lemon.jooq.tables.records.TAccountRecord;


/**
 * 用户账号信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccount extends TableImpl<TAccountRecord> {

    private static final long serialVersionUID = -1324707164;

    /**
     * The reference instance of <code>lemon.t_account</code>
     */
    public static final TAccount T_ACCOUNT = new TAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAccountRecord> getRecordType() {
        return TAccountRecord.class;
    }

    /**
     * The column <code>lemon.t_account.id</code>.
     */
    public final TableField<TAccountRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lemon.t_account.user_id</code>. 用户id
     */
    public final TableField<TAccountRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户id");

    /**
     * The column <code>lemon.t_account.identify_type</code>. 账号类型,1-平台账号
     */
    public final TableField<TAccountRecord, Integer> IDENTIFY_TYPE = createField("identify_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "账号类型,1-平台账号");

    /**
     * The column <code>lemon.t_account.identifier</code>. 登录标识，登录账号
     */
    public final TableField<TAccountRecord, String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "登录标识，登录账号");

    /**
     * The column <code>lemon.t_account.credential</code>. 密码凭证
     */
    public final TableField<TAccountRecord, String> CREDENTIAL = createField("credential", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "密码凭证");

    /**
     * The column <code>lemon.t_account.create_time</code>. 创建时间
     */
    public final TableField<TAccountRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>lemon.t_account.update_time</code>. 更新时间
     */
    public final TableField<TAccountRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>lemon.t_account.status</code>. 状态标识，0-正常，1-删除
     */
    public final TableField<TAccountRecord, Boolean> STATUS = createField("status", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "状态标识，0-正常，1-删除");

    /**
     * Create a <code>lemon.t_account</code> table reference
     */
    public TAccount() {
        this("t_account", null);
    }

    /**
     * Create an aliased <code>lemon.t_account</code> table reference
     */
    public TAccount(String alias) {
        this(alias, T_ACCOUNT);
    }

    private TAccount(String alias, Table<TAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private TAccount(String alias, Table<TAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户账号信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lemon.LEMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TAccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAccountRecord> getPrimaryKey() {
        return Keys.KEY_T_ACCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<TAccountRecord>>asList(Keys.KEY_T_ACCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccount as(String alias) {
        return new TAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TAccount rename(String name) {
        return new TAccount(name, null);
    }
}
