/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.joylife.lemon.jooq.Keys;
import top.joylife.lemon.jooq.Lemon;
import top.joylife.lemon.jooq.tables.records.TLinkRecord;


/**
 * 链接信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLink extends TableImpl<TLinkRecord> {

    private static final long serialVersionUID = -301202341;

    /**
     * The reference instance of <code>lemon.t_link</code>
     */
    public static final TLink T_LINK = new TLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TLinkRecord> getRecordType() {
        return TLinkRecord.class;
    }

    /**
     * The column <code>lemon.t_link.id</code>. id
     */
    public final TableField<TLinkRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "id");

    /**
     * The column <code>lemon.t_link.url</code>. url
     */
    public final TableField<TLinkRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "url");

    /**
     * The column <code>lemon.t_link.descri</code>. 连接描述
     */
    public final TableField<TLinkRecord, String> DESCRI = createField("descri", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "连接描述");

    /**
     * The column <code>lemon.t_link.name</code>. 连接名字
     */
    public final TableField<TLinkRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "连接名字");

    /**
     * The column <code>lemon.t_link.create_time</code>. 创建时间
     */
    public final TableField<TLinkRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>lemon.t_link.update_time</code>. 更新时间
     */
    public final TableField<TLinkRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>lemon.t_link.status</code>. 状态标识，0-未删除，1-删除
     */
    public final TableField<TLinkRecord, Boolean> STATUS = createField("status", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "状态标识，0-未删除，1-删除");

    /**
     * The column <code>lemon.t_link.image</code>. 图片
     */
    public final TableField<TLinkRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "图片");

    /**
     * Create a <code>lemon.t_link</code> table reference
     */
    public TLink() {
        this("t_link", null);
    }

    /**
     * Create an aliased <code>lemon.t_link</code> table reference
     */
    public TLink(String alias) {
        this(alias, T_LINK);
    }

    private TLink(String alias, Table<TLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private TLink(String alias, Table<TLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "链接信息表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lemon.LEMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TLinkRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TLinkRecord> getPrimaryKey() {
        return Keys.KEY_T_LINK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TLinkRecord>> getKeys() {
        return Arrays.<UniqueKey<TLinkRecord>>asList(Keys.KEY_T_LINK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLink as(String alias) {
        return new TLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TLink rename(String name) {
        return new TLink(name, null);
    }
}
