/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.joylife.lemon.jooq.Keys;
import top.joylife.lemon.jooq.Lemon;
import top.joylife.lemon.jooq.tables.records.TReplayRecord;


/**
 * 回复
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReplay extends TableImpl<TReplayRecord> {

    private static final long serialVersionUID = 983581186;

    /**
     * The reference instance of <code>lemon.t_replay</code>
     */
    public static final TReplay T_REPLAY = new TReplay();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TReplayRecord> getRecordType() {
        return TReplayRecord.class;
    }

    /**
     * The column <code>lemon.t_replay.id</code>.
     */
    public final TableField<TReplayRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lemon.t_replay.comment_id</code>. 评论id
     */
    public final TableField<TReplayRecord, Integer> COMMENT_ID = createField("comment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "评论id");

    /**
     * The column <code>lemon.t_replay.replay_id</code>. 回复人id
     */
    public final TableField<TReplayRecord, Integer> REPLAY_ID = createField("replay_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "回复人id");

    /**
     * The column <code>lemon.t_replay.replay_head_img</code>. 用户头像
     */
    public final TableField<TReplayRecord, String> REPLAY_HEAD_IMG = createField("replay_head_img", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "用户头像");

    /**
     * The column <code>lemon.t_replay.replay_name</code>. 用户名
     */
    public final TableField<TReplayRecord, String> REPLAY_NAME = createField("replay_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "用户名");

    /**
     * The column <code>lemon.t_replay.content</code>. 回复内容
     */
    public final TableField<TReplayRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "回复内容");

    /**
     * The column <code>lemon.t_replay.target_name</code>. 评论目标名字
     */
    public final TableField<TReplayRecord, String> TARGET_NAME = createField("target_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "评论目标名字");

    /**
     * The column <code>lemon.t_replay.target_id</code>. 评论目标id
     */
    public final TableField<TReplayRecord, Integer> TARGET_ID = createField("target_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "评论目标id");

    /**
     * The column <code>lemon.t_replay.create_time</code>. 创建时间
     */
    public final TableField<TReplayRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>lemon.t_replay.status</code>. 评论状态
     */
    public final TableField<TReplayRecord, Boolean> STATUS = createField("status", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "评论状态");

    /**
     * Create a <code>lemon.t_replay</code> table reference
     */
    public TReplay() {
        this("t_replay", null);
    }

    /**
     * Create an aliased <code>lemon.t_replay</code> table reference
     */
    public TReplay(String alias) {
        this(alias, T_REPLAY);
    }

    private TReplay(String alias, Table<TReplayRecord> aliased) {
        this(alias, aliased, null);
    }

    private TReplay(String alias, Table<TReplayRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "回复");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lemon.LEMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TReplayRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_REPLAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TReplayRecord> getPrimaryKey() {
        return Keys.KEY_T_REPLAY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TReplayRecord>> getKeys() {
        return Arrays.<UniqueKey<TReplayRecord>>asList(Keys.KEY_T_REPLAY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplay as(String alias) {
        return new TReplay(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TReplay rename(String name) {
        return new TReplay(name, null);
    }
}
