/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.joylife.lemon.jooq.Keys;
import top.joylife.lemon.jooq.Lemon;
import top.joylife.lemon.jooq.tables.records.TRoleResourceRecord;


/**
 * 角色资源表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleResource extends TableImpl<TRoleResourceRecord> {

    private static final long serialVersionUID = 2078634708;

    /**
     * The reference instance of <code>lemon.t_role_resource</code>
     */
    public static final TRoleResource T_ROLE_RESOURCE = new TRoleResource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoleResourceRecord> getRecordType() {
        return TRoleResourceRecord.class;
    }

    /**
     * The column <code>lemon.t_role_resource.id</code>.
     */
    public final TableField<TRoleResourceRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lemon.t_role_resource.role_id</code>. 角色id
     */
    public final TableField<TRoleResourceRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "角色id");

    /**
     * The column <code>lemon.t_role_resource.resource_id</code>. 资源id
     */
    public final TableField<TRoleResourceRecord, Integer> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "资源id");

    /**
     * Create a <code>lemon.t_role_resource</code> table reference
     */
    public TRoleResource() {
        this("t_role_resource", null);
    }

    /**
     * Create an aliased <code>lemon.t_role_resource</code> table reference
     */
    public TRoleResource(String alias) {
        this(alias, T_ROLE_RESOURCE);
    }

    private TRoleResource(String alias, Table<TRoleResourceRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRoleResource(String alias, Table<TRoleResourceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "角色资源表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lemon.LEMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TRoleResourceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_ROLE_RESOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TRoleResourceRecord> getPrimaryKey() {
        return Keys.KEY_T_ROLE_RESOURCE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TRoleResourceRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoleResourceRecord>>asList(Keys.KEY_T_ROLE_RESOURCE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRoleResource as(String alias) {
        return new TRoleResource(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoleResource rename(String name) {
        return new TRoleResource(name, null);
    }
}
