/*
 * This file is generated by jOOQ.
*/
package top.joylife.lemon.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import top.joylife.lemon.jooq.Keys;
import top.joylife.lemon.jooq.Lemon;
import top.joylife.lemon.jooq.tables.records.TUserRoleRecord;


/**
 * 用户角色关联
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRole extends TableImpl<TUserRoleRecord> {

    private static final long serialVersionUID = -300680933;

    /**
     * The reference instance of <code>lemon.t_user_role</code>
     */
    public static final TUserRole T_USER_ROLE = new TUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRoleRecord> getRecordType() {
        return TUserRoleRecord.class;
    }

    /**
     * The column <code>lemon.t_user_role.id</code>.
     */
    public final TableField<TUserRoleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lemon.t_user_role.user_id</code>. 用户id
     */
    public final TableField<TUserRoleRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户id");

    /**
     * The column <code>lemon.t_user_role.role_id</code>. 角色id
     */
    public final TableField<TUserRoleRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "角色id");

    /**
     * Create a <code>lemon.t_user_role</code> table reference
     */
    public TUserRole() {
        this("t_user_role", null);
    }

    /**
     * Create an aliased <code>lemon.t_user_role</code> table reference
     */
    public TUserRole(String alias) {
        this(alias, T_USER_ROLE);
    }

    private TUserRole(String alias, Table<TUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserRole(String alias, Table<TUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户角色关联");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lemon.LEMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TUserRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_USER_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserRoleRecord>>asList(Keys.KEY_T_USER_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRole as(String alias) {
        return new TUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRole rename(String name) {
        return new TUserRole(name, null);
    }
}
